### ISSUE TITLE
Running project on Hololens.

### ISSUE THREAD

**Issue by PubEne** [foomanchu1234/holorabbit#1]
Is there any way, that You can help with implementing Your solution on HoloLens? I've stuck on point 6 - The RabbitClient is the main interface that is used within your project. I am failing every time to connect with my Rabbit localhost.

**Comment by fuadmefleh** [comment]
Are you using an ip address of localhost or 127.0.0.1?  I don't think it works with just localhost string and will require an actual IP, I may be wrong.
